<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <MdReaderOut Condition="'$(MdReaderOut)' == ''">..\..\out\</MdReaderOut>
    <OutputPath>$(MdReaderOut)</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MdReader.Core\MdReader.Core.csproj" />
    <ProjectReference Include="..\MdReader.Bridge\MdReader.Bridge.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
</Project>
